### ISSUE TITLE
Missing Pre-alignments with RefGenie in v0.10.0

### ISSUE THREAD

**Issue by CriticalSci** [databio/peppro#90]
Hi @jpsmith5,

I recently installed PEPPRO on our cluster following the conda installation instructions. Everything appears to run fine except for the pre-alignment step. No matter what I define in the looper yaml input file, the pre-alignment to human_rDNA never happens and gets skipped despite having all the necessary RefGenie assets.

PEPPRO_log.md:
```markdown
### Arguments passed to pipeline:
* `prealignment_index`:  `[]`
* `prealignment_names`:  `[]`
### Prealignments (04-13 18:55:48) elapsed: 251.0 _TIME_

You may use `--prealignment-index` to align to references before the genome alignment step. See http://peppro.databio.org/en/latest/ for documentation.
```

`refgenie list` lists:
genome | assets
-------- | -------
hg38 | fasta, bowtie2_index, ensembl_gtf, ensembl_rb, refgene_anno, feat_annotation
human_rDNA | fasta, bowtie2_index

I defined the prealignments in the yaml as per the [examples in the repo](https://github.com/databio/peppro/tree/master/examples/meta):

```yaml
  imply:
    - if:
        organism: ["human", "Homo sapiens", "Human", "Homo_sapiens"]
      then:
        genome: "hg38"
        prealignments: ["human_rDNA"] # also tried "human_rDNA"
```

The same input data/yaml/csv runs fine on the 0.9.11 PEPPRO  install on a local machine though. I noticed there's been a lot of changes regarding RefGenie / prealignment code in [peppro.py](https://github.com/databio/peppro/blob/master/pipelines/peppro.py) since 0.9.11 so perhaps you have a better idea of what could be going wrong with 0.10.0? Cheers!
