### ISSUE TITLE
Recovery of mitochondrial DNA reads

### ISSUE THREAD

**Issue by Noam-St** [databio/peppro#91]
Hello,
Everything is working great on my samples. However, I need the mitochondrial DNA reads and Peppro automatically filters them as part of the serial alignment pipeline. Is there any way to disable this behavior?
I can of course manually take them from the `{sample}_fail_qc.bam` files, and merge them with the final outputs, but I am hoping there is a better approach.

**Comment by jpsmith5** [comment]
Hey @Noam-St,

I just added an option to keep those mitochondrial reads in downstream steps with the newest release. So, if you pull the repo again you could now add `--keep-mito` via the command line interface, or the equivalent in a configuration file would be like so (see the `keep_mito: True` line):
```
# Run test sample through PEPPRO
name: test

pep_version: 2.0.0
sample_table: peppro_test.csv

looper:
  output_dir: peppro_test
  pipeline_interfaces: ../../project_pipeline_interface.yaml  # PATH to the directory where looper will find the pipeline repository. 

sample_modifiers:
  append:
    pipeline_interfaces: ../../sample_pipeline_interface.yaml # PATH to the directory where looper will 
    keep_mito: True
  derive:
    attributes: [read1]
    sources:
        R1: "examples/data/{sample_name}_r1.fq.gz"
  imply:
    - if:
        organism: ["human", "Homo sapiens", "Human", "Homo_sapiens"]
      then:
        genome: hg38
        prealignment_names: ["human_rDNA"]
```

In my very quick test case it looks to be working, so if you hit an issue with that let me know.
